sudo: required

group: edge

services:
  - docker

env:
  global:
    - GRAPHITE_VERSION=${GRAPHITE_VERSION:-1.1.5}
    - PYTHON_VERSION=${PYTHON_VERSION:-3}
    - BUILD_TYPE=stable
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: build and test
      script:
        - make
        - make start
        - make test
        - make stop

    - stage: push latest docker image
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag  ${USER}/graphite:latest ${DOCKER_USERNAME}/docker-graphite:latest
        - docker push ${DOCKER_USERNAME}/docker-graphite:latest
        - docker logout

    - stage: push version docker image
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag  ${USER}/graphite:latest ${DOCKER_USERNAME}/docker-graphite:${GRAPHITE_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-graphite:${GRAPHITE_VERSION}
        - docker logout
