sudo: required

group: edge

services:
  - docker

install:
  - docker build --tag bodsch/docker-graphite .
  - docker run --detach --name graphite bodsch/docker-graphite

script:
  - docker ps | grep -q graphite

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-graphite/trigger/${DOCKER_HUB_TOKEN}/
