sudo: required

group: edge

services:
  - docker

env:
  global:
    - GRAPHITE_VERSION=${GRAPHITE_VERSION:-1.1.4}
    - PYTHON_VERSION=${PYTHON_VERSION:-3}
    - BUILD_TYPE=stable
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: build and test
      script:
        - make
        - docker run --detach --name graphite --publish 8088:8080 bodsch/docker-graphite:${GRAPHITE_VERSION}
        - sleep 10s
        - docker ps | grep -q graphite
        - curl --silent --fail http://localhost:8088/browser/header

    - stage: push latest docker image
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag ${DOCKER_USERNAME}/docker-graphite:${GRAPHITE_VERSION} ${DOCKER_USERNAME}/docker-graphite:latest
        - docker push ${DOCKER_USERNAME}/docker-graphite:latest
        - docker logout

    - stage: push version docker image
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-graphite:${GRAPHITE_VERSION}
        - docker logout
