sudo: required

group: edge

services:
  - docker

env:
  global:
    - GRAPHITE_VERSION=${GRAPHITE_VERSION:-1.1.3}
    - PYTHON_VERSION=2
    - BUILD_TYPE=stable
    - BUILD_DATE=$(date +"%Y-%m-%d")

script:
  - make
  - docker run --detach --name graphite bodsch/docker-graphite
  - docker ps | grep -q graphite

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-graphite/trigger/${DOCKER_HUB_TOKEN}/
