---
version: '3.3'

services:

  graphite:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - VCS_REF=${GIT_SHA1}
        - BUILD_DATE=${BUILD_DATE}
        - BUILD_VERSION=${BUILD_VERSION}
        - BUILD_TYPE=${BUILD_TYPE}
        - GRAPHITE_VERSION=${GRAPHITE_VERSION}
    container_name: graphite
    hostname: graphite
    ports:
      - 2003:2003
      - 8080:8080
      - 9001:9001
